const mongoose = require("mongoose");

const walletSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User", // Reference to the User model
    required: true,
  },
  amount: {
    type: Number,
    required: true,
  },
  transactionDate: {
    type: Date,
    default: Date.now, // Default to the current date and time
  },
  transactionId: {
    type: String,
    required: true, // Unique transaction ID (can be generated by payment gateway)
  },
});

// add these four fields in the wallet page to show transactions

const Wallet = mongoose.model("Wallet", walletSchema);

module.exports = Wallet;
